### PR TITLE
Create Typing_speed_test.py

### LINKED ISSUE #252: Typing speed test
## Suggest a new script for the project
Typing speed tester using python

### Describe the new script you want
I want to add a script for a typing speed tester GUI which will tell users their typing speed.

## Do you want to work on this?
-  yes

### PR DESCRIPTION
**Pull request by lovishprabhakar**
Added a typing speed tester GUI using python

# Description

A python based GUI that indicates the user's typing speed by making them type different words.

Fixes #252 

## Type of change

- [ ] New Script (non-breaking change which adds a new script to the repository)

## Has This Been Tested?

- [ ] I confirm that I have tested my script locally and verified that it works as intended.

## Screenshot (if applicable)
image

image

Output(time taken in seconds to type the word):

image

## Checklist:

- [ ] I have gone through the contributing guidelines before making this Pull Request.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by OBITORASU** [comment]
Install black with `pip install black` and run it with `black .` in the root directory of your script.

**Comment by lovishprabhakar02** [comment]
> Install black with `pip install black` and run it with `black .` in the root directory of your script.

sorry sir could you please elaborate a little, as I am new to python programming. Thank you.

**Comment by OBITORASU** [comment]
> > Install black with `pip install black` and run it with `black .` in the root directory of your script.
> 
> sorry sir could you please elaborate a little, as I am new to python programming. Thank you.

Lets say you are working on your script in the following directory `coding/General-Purpose-Scripts/typingtest`. So, all you have to do is open a terminal inside your working directory and type `pip install black`, this will install the black autolinter on your system, after that you can run black with `black .` which will recursively run black on all the python files in starting from your working directory. Black goes through all of your python files and enforces linting standards and does the proper linting on your behalf automatically, once black has finished doing its job just push the changes it made to the linting.

**Comment by lovishprabhakar02** [comment]
> Just a few more things before I can merge, your requirements.txt is in wrong format. To make a proper requirement.txt you use this format `packagename==version` or `packagename>=version` and other variations. Additionally, you need to add a readme for your script telling the user how to use it. Also, dont forget to add your script to the list of scripts on our main readme.

Done sir, added package versions in requirements.txt file and also created a Readme.md file.

**Comment by lovishprabhakar02** [comment]
Thank you for all your help sir.

**Pull request merged**
