### PR TITLE
Youtube playlist duration

### LINKED ISSUE #128: Calculate the Duration of any YouTube playlist
### Describe the new script you want
The main issue in YouTube is  that it does not show the total time duration of any playlist. 
I will create a script to calculate the time duration of any YouTube playlist.

### Describe the solution you'd like us to follow
Initially the user will enter the playlist link for which the user want the time duration. I will use Google Cloud Console's YouTubeAPI to scrape to all video details in the playlist to calculate the time duration.

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

### PR DESCRIPTION
**Pull request by dishant26**
# Description

Please include a general summary of the change and/or which issue it fixed. 

Fixes #128 

## Type of change

Please delete options that are not relevant.

- [x] New Script (non-breaking change which adds a new script to the repository)

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Screenshot (if applicable)

image

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by dishant26** [comment]
> @OBITORASU you can merge this.

And I have also updated the main README.

**Comment by OBITORASU** [comment]
It showing conflict because the main README gets updated with every PR merge, so you have to fetch upstream and merge the changes to your own fork as well.

**Comment by dishant26** [comment]
All Done @OBITORASU . 
Just the conflict is that I have added new row for this script in the Main README.md. 
Now it fine to merge this :)

**Comment by OBITORASU** [comment]
@dishant26 really sorry I merged a PR before yours and that resulted in this merge conflict. Could you please fix it again and I will have this merged right now. Thanks!

**Comment by dishant26** [comment]
@OBITORASU There was some problems in that pull requests and my repo so I forked again and created a new pull request. U can merge it. #188

**Comment by OBITORASU** [comment]
Closing this in favor of #188

**Pull request closed without merging**
