### PR TITLE
fixed contribution

### LINKED ISSUE #106: pie chart maker
### Describe the new script you want
A clear and concise description of what the new script is all about. Ex. I want an email script which [...]
I want to add a python command line script that parses a list of user input and displays it on a pie chart

### Describe the solution you'd like us to follow
A clear and concise description of how you want this script to work.

## Do you want to work on this?
- [x ] yes
- [ ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

### PR DESCRIPTION
**Pull request by AcousticCh**
# Description

Please include a general summary of the change and/or which issue it fixed. 

Fixes #106 
## Type of change

Please delete options that are not relevant.

- [ x] New Script (non-breaking change which adds a new script to the repository)

## Has This Been Tested?

- [x ] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [ x] I have gone through the contributing guidelines before making this Pull Request.
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

### CODE REVIEW

**Comment by OBITORASU** [comment]
LGTM!

**Comment by OBITORASU** [comment]
Please add a requirements.txt and add the process of installing requirements in the readme then this should be good to merge.

**Comment by AcousticCh** [comment]
requirements.txt added

**Comment by OBITORASU** [comment]
LGTM!

**Pull request merged**
