### PR TITLE
Add Audio Book

### LINKED ISSUE #37: PDF Audiobook Reader
### Describe the new script you want
A script that converts pdf texts-to-speech.

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context
A python script to convert text-to-speech using python modules.

### PR DESCRIPTION
**Pull request by ignaviaa**
# Description
AudioBook made with Python to help the user to listen to the pdf file of their choices.
Fixes #37 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] New Script (non-breaking change which adds a new script to the repository)
- [x] This change requires a documentation update

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by OBITORASU** [comment]
Please edit the main readme and add your script to the list :)

**Comment by ignaviaa** [comment]
@OBITORASU  sureee

**Comment by ignaviaa** [comment]
have updated the `README.md` file you can merge it now @OBITORASU

**Comment by ignaviaa** [comment]
@OBITORASU can you please give the `hacktoberfest-accepted` tag here.

**Comment by OBITORASU** [comment]
> @OBITORASU can you please give the `hacktoberfest-accepted` tag here.

Merged request already count, the tag isn't explicitly needed.

**Pull request merged**
