### PR TITLE
Water Reminder Discord Bot 

### PR DESCRIPTION
**Pull request by 0xMukesh**
# Description

Added a new project to the scripts folder, Water Reminder Discord bot 
Fixes #(issue number)

## Type of change 

- [x] New Script (non-breaking change which adds a new script to the repository)

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Screenshot (if applicable)
image

image

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by OBITORASU** [comment]
Can you port this as a basic python script which does the same and runs in the background instead of making it a specialty discord bot because that certainly limits the usability of this script? On top of that add a requirements.txt and some documentation in the form of a proper readme.

**Comment by OBITORASU** [comment]
> > Can you port this as a basic python script which does the same and runs in the background instead of making it a specialty discord bot because that certainly limits the usability of this script?
> 
> Uh... I guess there is a water reminder python script already sweat_smile
> 
You can port your main.py as a normal locally run python script instead of turning it into a discord bot. As for the water reminder script being already present in our repository, I can't recall can you link me to it?

**Comment by Kira272921** [comment]
> > > Can you port this as a basic python script which does the same and runs in the background instead of making it a specialty discord bot because that certainly limits the usability of this script?
> > 
> > 
> > Uh... I guess there is a water reminder python script already sweat_smile
> 
> You can port your main.py as a normal locally run python script instead of turning it into a discord bot. As for the water reminder script being already present in our repository, I can't recall can you link me to it?

Ohh shoot!!
I was checking my fork where I named the folder for the water reminder discord bot script as water reminder so I got confused 
My bad 

I will work on the local water reminder python script :+1:

**Comment by Kira272921** [comment]
@OBITORASU 👍 I have made it into local python script

**Comment by OBITORASU** [comment]
Looks good, make sure the lint checks pass and add this script to main readme.

**Pull request merged**
