### PR TITLE
Email phone extractor

### LINKED ISSUE #39: Email-Phone Number Extractor
### Describe the new script you want
Extract emails and phone numbers from the text of clipboard copied
or an input file and creates two csvs for it having email and phone number separately.

## Do you want to work on this?
- [x] yes
- [ ] no.

### PR DESCRIPTION
**Pull request by gitshashwat**
# Description

A script to have an email and a phone number extractor from text files/clipboard.

(Extract emails and phone numbers from the text of clipboard copied
or an input file and creates two csvs for it having email and phone number separately.)

Fixes #39 

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by gitshashwat** [comment]
@soham4abc Updated the branch and opened a new pull request!

**Comment by soham4abc** [comment]
@OBITORASU  Please do have a look!

**Comment by OBITORASU** [comment]
Sweet! Merged.

**Comment by gitshashwat** [comment]
@OBITORASU Please do add the label hacktober-accepted.

**Comment by OBITORASU** [comment]
You don't need that label if your PR got merged. Some repository's use that specifically to greenlight PRs when their repository itself doesn't have the hacktoberfest topic added to it. This is an anti-spam feature. Your merged PR should show up on your Hacktoberfest profile in a few minutes once they update it :)

**Pull request merged**
