### PR TITLE
Convert Word file to PDF format #92

### LINKED ISSUE #92: Convert Word file to PDF format
### Code Description
Python script that converts doc file to pdf format. Comes handy when you have a bulk or single file conversion!

### Description of the solution
using docx2pdf module for file conversion and tkinter for GUI which enables easy use for the end user.

## Do you want to work on this?
- [x] yes
- [ ] no

### PR DESCRIPTION
**Pull request by BasuDevTyagi10**
# Description

Please include a general summary of the change and/or which issue it fixed. 

Fixes #92 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] New Script (non-breaking change which adds a new script to the repository)
- [x] This change requires a documentation update

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by rijusougata13** [comment]
Please fix the merge conflict !!!

**Comment by rijusougata13** [comment]
Please fix the merge conflict !!

**Comment by BasuDevTyagi10** [comment]
will do..

**Comment by BasuDevTyagi10** [comment]
@rijusougata13 please review the PR.

**Comment by rijusougata13** [comment]
> @rijusougata13 please review the PR.

hi please fix the linting issue using black (mentioned in contributor guidelines)

**Comment by BasuDevTyagi10** [comment]
@rijusougata13 please review the new PR for the same issue.
[https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/pull/149/](https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/pull/149/)

**Pull request closed without merging**
