### PR TITLE
Made gpscript script installer for install, update, remove a single script using gpscript command, and added guidelines in README.md

### PR DESCRIPTION
**Pull request by ujjwalkar0**
# Description

I made General Purpose Script Installer gpscript by which one can Install, update, remove any script. Installed scripts can be called from anywhere of virtualenv. I have made some changes like rename folders, add absolute location of path so that scripts can be call from anywhere. In README.md I write how to Install scripts using gpscript installer, and give a developer guideline how to set path such that their will no problem occur if it's called from anywhere. 

Fixes #(issue number)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Has This Been Tested?

- [ ] I confirm that I have tested my script locally and verified that it works as intended.

## Screenshot (if applicable)
image

## Checklist:

- [ ] I have gone through the contributing guidelines before making this Pull Request. 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings.

### CODE REVIEW

**Comment by OBITORASU** [comment]
Hey great work on this one! Can you make sure the lint checks are passing and this should be good to merge.

**Comment by OBITORASU** [comment]
Also remove the vscode settings.

**Comment by ujjwalkar0** [comment]
> Hey great work on this one! Can you make sure the lint checks are passing and this should be good to merge.

In my machine its learn properly but here in build, one check failed. I can't find the error. Is it okey ?
Log is

```
Run black --check --diff .
  black --check --diff .
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
--- scripts/AI_Workout_Tracker/home.py	2021-11-05 18:31:25.067819 +0000
+++ scripts/AI_Workout_Tracker/home.py	2021-11-05 18:31:29.263787 +0000
would reformat scripts/AI_Workout_Tracker/home.py
@@ -3,23 +3,25 @@
 from PIL import ImageTk, Image
 import cv2
 import mediapipe as mp
 import imageio
 import numpy as np
-    
+
 mp_drawing = mp.solutions.drawing_utils
 mp_pose = mp.solutions.pose
 from mediapipe.python.solutions.pose import PoseLandmark
 from exercise import workout
 
 import os
+
 base_dir = os.path.dirname(os.path.realpath(__file__))
 
 root = Tk()
 root.attributes("-fullscreen", True)
 root.geometry(f"{root.winfo_screenwidth()}x{root.winfo_screenheight()}")
 root["bg"] = "black"
+
 
 def opencameraWindow():
     lst = []
     global cam_bg, startt_btn, stop_btn, camera_window, imgcanvas, begin
     stop = True
--- scripts/CryptoCurrencyTracker/main.py	2021-11-05 18:31:25.203821 +0000
+++ scripts/CryptoCurrencyTracker/main.py	2021-11-05 18:31:29.436684 +0000
@@ -4,10 +4,11 @@
 import time
 import pandas as pd
 import requests
 
 import os
+
 base_dir = os.path.dirname(os.path.realpath(__file__))
 
 c = 0
 # some coin names to be scraped.
 CoinsNames = ["Bitcoin-USD", "Ethereum-USD", "HEX-USD", "Cardano-USD", "Tether-USD"]
would reformat scripts/CryptoCurrencyTracker/main.py
--- scripts/alarm-clock/alarm_clock.py	2021-11-05 18:31:25.247822 +0000
+++ scripts/alarm-clock/alarm_clock.py	2021-11-05 18:31:30.256227 +0000
@@ -3,16 +3,19 @@
 from datetime import datetime
 from plyer import notification
 from playsound import playsound
 
 import os
+
 base_dir = os.path.dirname(os.path.realpath(__file__))
 
 # import pyobjus
 
 msg = "Wake Up!"  # your default remainder/alarm message
-audio_path = f"{base_dir}/alarm-songs/ncs_high.mp3"  # your default remainder/alarm audio
+audio_path = (
+    f"{base_dir}/alarm-songs/ncs_high.mp3"  # your default remainder/alarm audio
+)
 
 
 def show_notification(title_msg, message):
     """shows notification if proper permissions given and modules installed"""
     print("notification displayed")
would reformat scripts/alarm-clock/alarm_clock.py
Oh no! 💥 💔 💥
3 files would be reformatted, 84 files would be left unchanged.
Error: Process completed with exit code 1.

````

**Comment by ujjwalkar0** [comment]
> Also remove the vscode settings.

ok, I will remove

**Comment by ujjwalkar0** [comment]
.vscode deleted

**Comment by OBITORASU** [comment]
> > Hey great work on this one! Can you make sure the lint checks are passing and this should be good to merge.
> 
> Yes, I make sure. Only one lint check failed in `black --check --diff` with `Error: Process completed with exit code 1.` because I have reformatted some folder and file. Everything runs properly in my machine.

Just rank black . at the source of the repository and push any changes black makes. That will make sure the lint checks pass in the workflow.

**Comment by ujjwalkar0** [comment]
> > > Hey great work on this one! Can you make sure the lint checks are passing and this should be good to merge.
> > 
> > 
> > Yes, I make sure. Only one lint check failed in `black --check --diff` with `Error: Process completed with exit code 1.` because I have reformatted some folder and file. Everything runs properly in my machine.
> 
> Just rank black . at the source of the repository and push any changes black makes. That will make sure the lint checks pass in the workflow.

I can't understand.

**Comment by ujjwalkar0** [comment]
Now it's ready to marge

**Comment by OBITORASU** [comment]
Thanks for the contribution! If you want you can create another PR for updating the scripts in `packages.json`.

**Comment by ujjwalkar0** [comment]
> Thanks for the contribution! If you want you can create another PR for updating the scripts in `packages.json`.

Yes, I will update packages.json

**Comment by OBITORASU** [comment]
> > Thanks for the contribution! If you want you can create another PR for updating the scripts in `packages.json`.
> 
> Yes, I will update packages.json

Drop a PR when you are done :)

**Pull request merged**
