### PR TITLE
add: add new script to generate JSON files from YAML files

### PR DESCRIPTION
**Pull request by antoooks**
- add main class
- add example directory
- handle errors and empty folders

# Description

Addresses #82 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] New Script (non-breaking change which adds a new script to the repository)
- [ ] This change requires a documentation update

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Screenshot (if applicable)
N/A

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by OBITORASU — CHANGES_REQUESTED** [review]
Add a readme documenting the script and edit the main readme to add your script to the list of available scripts.

**Comment by antoooks** [comment]
Added readme @OBITORASU  :)

**Comment by OBITORASU** [comment]
Left a review for you.

**Review by OBITORASU — CHANGES_REQUESTED** [review]

**Review by OBITORASU — APPROVED** [review]
LGTM!

**Pull request merged**
