### PR TITLE
Fixed issue #138 : Image Format Converter 

### PR DESCRIPTION
**Pull request by MahirRohatgi18**
# Description

Added ImageConversion.py with .Black formatting and updated README.md 

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by rijusougata13** [comment]
Please add the issue no also. Like ``` Fixes #<issue no> ```

**Comment by MahirRohatgi18** [comment]
> Please add the issue no also in Pull Request . Like `Fixes #<issue no>`

Done

**Comment by rijusougata13** [comment]
also, link your script in the main readme file.

**Comment by MahirRohatgi18** [comment]
> also, link your script in the main readme file.

not able to link my script in the main readme file cause you still havent accepted the pull request .
how do i get the address of the script ?

**Comment by rijusougata13** [comment]
> > also, link your script in the main readme file.
> 
> not able to link my script in the main readme file cause you still havent accepted the pull request . how do i get the address of the script ?

No. You just have to link your PR.  like https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/pull/157

**Comment by MahirRohatgi18** [comment]
> > > also, link your script in the main readme file.
> > 
> > 
> > not able to link my script in the main readme file cause you still havent accepted the pull request . how do i get the address of the script ?
> 
> No. You just have to link your PR. like #157

Alright thanks :) 
Done with linking the script in the main readme file

**Pull request merged**
