### PR TITLE
Spectrogram

### LINKED ISSUE #145: Spectrogram
## Suggest a new script for the project
A spectrogram made using matplotlib. 

### Describe the new script you want
Spectrogram which can be used to visualize audio files. Useful in CTF's / detect steganography

## Do you want to work on this?
- [ x] yes
- [ ] no

### PR DESCRIPTION
**Pull request by DCYPHERR**
# Description

Fixes #145 
## Type of change

Please delete options that are not relevant.

- [ x] New Script (non-breaking change which adds a new script to the repository)

## Has This Been Tested?

- [x ] I confirm that I have tested my script locally and verified that it works as intended.

## Screenshot (if applicable)
https://imgur.com/a/uzBQCe9

## Checklist:

- [x ] I have gone through the contributing guidelines before making this Pull Request.
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings

### CODE REVIEW

**Comment by DCYPHERR** [comment]
Kindly Review. @OBITORASU

**Comment by OBITORASU** [comment]
Add a requirements.txt or document the install process of the dependencies using pip in thr readme.

**Comment by DCYPHERR** [comment]
> 
> 
> Add a requirements.txt or document the install process of the dependencies using pip in thr readme.

Done!

**Comment by DCYPHERR** [comment]
> 
> 
> Add a requirements.txt or document the install process of the dependencies using pip in thr readme.

Kindly re-review @OBITORASU

**Comment by OBITORASU** [comment]
LGTM!

**Pull request merged**
