### PR TITLE
News down

### LINKED ISSUE #14: Newsdown has unused imports
### Mention the script affected by the bug
Newsdown

### Describe the bug
The script seems to have imported a few things which were never really used in the script itself.

### Expected behavior
Unused imports should be removed and the script should be tested at least once to see if it runs after the changes.

## Do you want to work on this?
- [ ] yes
- [x] no

### PR DESCRIPTION
**Pull request by bartick**
# Description

Removed all unnecessary imports and libraries. I have locally checked the script (With Best of my knowledge) and it works just as intended.

Fixes #14 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New Script (non-breaking change which adds a new script to the repository)
- [ ] This change requires a documentation update

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by OBITORASU — CHANGES_REQUESTED** [review]

**Comment by OBITORASU** [comment]
Did you test the latest commit locally?

**Comment by OBITORASU** [comment]
Looks good, just confirm the script runs as intended locally and it will be good to merge!

**Comment by bartick** [comment]
Sorry for doing it twice. Yes I have tested it locally. I totally missed redundant imports. I tried removing `from tkinter import ttk` but for some reason it was showing error so I removed `from tkinter import *`

**Comment by belelaritra** [comment]
@bartick Please remove [unused](https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/blob/main/scripts/NewsDown/main.py#L1-L6) packages (Except [L3](https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/blob/main/scripts/NewsDown/requirements.txt#L3) , [L11](https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/blob/main/scripts/NewsDown/requirements.txt#L11), [L22](https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/blob/main/scripts/NewsDown/requirements.txt#L22)) from [requirements.txt](https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/blob/main/scripts/NewsDown/requirements.txt)

**Comment by bartick** [comment]
@belelaritra Thanks for letting me know.
Yes I did it. The project really took 10 less libraries.
It now contains 15 total requirements

**Comment by OBITORASU** [comment]
@belelaritra doing God's work.

**Pull request merged**
