### PR TITLE
Add script to fetch lyrics of a song

### LINKED ISSUE #40: Script to fetch lyrics of a song
### Describe the new script you want
A Python3 script using Genius API to fetch the lyrics of a song given as input and store it in a text file.

## Do you want to work on this?
- [x] yes
- [ ] no

### PR DESCRIPTION
**Pull request by adviksinghania**
# Description
A Python3 script to fetch the lyrics of a song using lyricsgenius module and Genius API.
Fixes #40 

## Type of change

- [x] New Script (non-breaking change which adds a new script to the repository)

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by OBITORASU** [comment]
Can you please fix the merge conflicts?

**Comment by OBITORASU** [comment]
LGTM! Great work.

**Comment by adviksinghania** [comment]
Thanks. @OBITORASU can I get your LinkedIn profile to stay connected ? I'm also interested in Pentest and OSCP

**Comment by OBITORASU** [comment]
I don't use LinkedIn at all you, on the contrary I am very active on Discord, you can keep in touch with me there. Drop in on the GDSC RCCIIT Discord server and say hi :) you can find the link [here](https://dscrcciit.com).

**Pull request merged**
