### PR TITLE
File organizer

### LINKED ISSUE #32: Files Organizer
Files Organizer

### Describe the new script you want
The script will be written in python and will automatically sort files in a folder depending on there file types in separate folders.

## Do you want to work on this?
- [x] yes
- [ ] no

### PR DESCRIPTION
**Pull request by JaniniRami**
# Description
Added a file organizer script that automatically sorts files in separate folders depending on their type.

Fixes #32 

## Type of change
- [x] New Script (non-breaking change which adds a new script to the repository)

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by OBITORASU** [comment]
Run the `black` autolinter locally to make sure the lint checks pass.

**Comment by JaniniRami** [comment]
How do I do that?

**Comment by JaniniRami** [comment]
Fixed it

**Comment by OBITORASU** [comment]
LGTM!

**Pull request merged**
