### PR TITLE
handwriting script added

### LINKED ISSUE #83: Text to Handwritten
I want to add a mini project which converts Text-to-handwritten image. It can converts text content to an image that looks like handwriting. 
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by kiranbaby14**
# Description

Added basic script to convert a text or a text file to handwritten images.

Fixes #83

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] New Script (non-breaking change which adds a new script to the repository)
- [x] This change requires a documentation update

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by kiranbaby14** [comment]
This is a new feature to be added to the repository for the issue #83. Please evaluate it and inform me of any corrections.

**Comment by kiranbaby14** [comment]
Kindly review @OBITORASU

**Comment by OBITORASU** [comment]
Add a requirements.txt

**Comment by kiranbaby14** [comment]
@OBITORASU requirement.txt added

**Comment by kiranbaby14** [comment]
> Some of the dependencies are unnecessary and should not be there in the requirements.txt, could you remove the unnecessary ones?

well when i install "pywhatkit library" all of the other ones also gets installed.
so should i only give pywhatkit inside requirements.txt?

**Comment by kiranbaby14** [comment]
@OBITORASU is this ok?

**Comment by kiranbaby14** [comment]
> I think you missed pillow.

its automatically added along with "pywhatkit".

**Comment by kiranbaby14** [comment]
> I think you missed pillow.

@OBITORASU updated could you check now

**Comment by OBITORASU** [comment]
LGTM!

**Pull request merged**
