### PR TITLE
Added Covid Tracker Script

### PR DESCRIPTION
**Pull request by GigaMoksh**
Please include a general summary of the change and/or which issue it fixed. 
Added Covid Tracker script which tracks no of cases, no of deaths and cases recovered worldwide and in every country.

## Type of change
Added a new Script

Please delete options that are not relevant.
- [x] New Script (non-breaking change which adds a new script to the repository)

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.
- [ ] 
## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by GigaMoksh** [comment]
I don't understand what's wrong in the code, everything works fine in my laptop.

**Comment by OBITORASU** [comment]
> 
> 
> I don't understand what's wrong in the code, everything works fine in my laptop.

The linting. Run black autolinter locally it will do the linting for you. That aside, please move the icon images to a dedicated `images` directory and add your script the list of scripts on the main readme.

**Comment by GigaMoksh** [comment]
> > I don't understand what's wrong in the code, everything works fine in my laptop.
> 
> The linting. Run black autolinter locally it will do the linting for you. That aside, please move the icon images to a dedicated `images` directory and add your script the list of scripts on the main readme.

okay will do

**Comment by GigaMoksh** [comment]
@OBITORASU done!

**Comment by OBITORASU** [comment]
Can you please fix the merge conflict.

**Comment by GigaMoksh** [comment]
> Can you please fix the merge conflict.

Done!

**Comment by OBITORASU** [comment]
Still need to fix the linting. You can read about how you can do that with black in the CONTRIBUTING.md file in `.github` directory of our repository.

**Comment by GigaMoksh** [comment]
> Still need to fix the linting. You can read about how you can do that with black in the CONTRIBUTING.md file in `.github` directory of our repository.

Done!

**Pull request merged**
