### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 1305Tanmay**
# Description

Please include a general summary of the change and/or which issue it fixed. 

Fixes #(issue number)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New Script (non-breaking change which adds a new script to the repository)
- [ ] This change requires a documentation update

## Has This Been Tested?

- [ ] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [ ] I have gone through the contributing guidelines before making this Pull Request.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by OBITORASU** [comment]
@rijusougata13 have a look.

**Comment by rijusougata13** [comment]
Sorry! Currently we dont want a readme file under script folder. Closing the PR.

**Comment by 1305Tanmay** [comment]
no problem

**Comment by IamBikramPurkait** [comment]
> Sorry! This will be counted as a valid pull request . Closing this PR. Good Luck !

I think you mean, This will `not` be counted as a valid pull request .

**Comment by rijusougata13** [comment]
@IamBikramPurkait  🥇

**Pull request closed without merging**
