### PR TITLE
Added Twitter Scraper

### PR DESCRIPTION
**Pull request by dishant26**
# Description

Please include a general summary of the change and/or which issue it fixed. 

Fixes #(issue number)
#110 

## Type of change

Please delete options that are not relevant.

- [x] New Script (non-breaking change which adds a new script to the repository)

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Screenshot (if applicable)
image

image

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by dishant26** [comment]
@OBITORASU you can merge this and label this as **hacktober-accepted**

**Comment by OBITORASU** [comment]
Add your script to the main readme of the repository.

**Comment by dishant26** [comment]
Done :)

**Comment by OBITORASU** [comment]
> Done :)

Last thing make sure the lint checks pass before I can merge. Use black autolinter for this, it will do all the linting for you. `pip install black` then `black .`

**Comment by dishant26** [comment]
> > Done :)
> 
> Last thing make sure the lint checks pass before I can merge. Use black autolinter for this, it will do all the linting for you. `pip install black` then `black .`

Done. All checks passed

**Comment by dishant26** [comment]
> > > Done :)
> > 
> > 
> > Last thing make sure the lint checks pass before I can merge. Use black autolinter for this, it will do all the linting for you. `pip install black` then `black .`
> 
> Done. All checks passed

@OBITORASU Now you can merge this and add the hacktober-accepted label

**Comment by OBITORASU** [comment]
You don't need the label merged PRs count towards your progress :)

**Comment by dishant26** [comment]
> You don't need the label merged PRs count towards your progress :)

Okay fine thanks :)

**Pull request merged**
