### PR TITLE
Cp template

### PR DESCRIPTION
**Pull request by Kaustuv942**
# Description

Added easy to use competitive programming template maker before contests, which would make your cpp files organized.

Please delete options that are not relevant.

- [x]  New feature (non-breaking change which adds functionality)

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Screenshot (if applicable)

a4a7ae1b-bc17-4748-a6a3-1e9499feee24
da2208c8-d502-4559-b801-5ac59f9858bd

### CODE REVIEW

**Comment by Kaustuv942** [comment]
Issue #26

**Comment by rijusougata13** [comment]
LGTM !!

**Comment by OBITORASU** [comment]
Please edit the main README and add your script there.

**Comment by OBITORASU** [comment]
Ty for your contribution

**Comment by Kaustuv942** [comment]
Please check

**Comment by Kaustuv942** [comment]
Please add the 'hacktoberfest-accepted' label

**Pull request merged**
